greensaleuz/greensale-webapi

src/GreenSale.DataAccess/Interfaces/Users/IUserRepository.cs
src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs

DATAACCES : User Add GetbyPhono

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Service/Auth/AuthServise.cs

SERVISE : Service Auth AuthService Register

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Service/Auth/TokenService.cs
src/GreenSale.WebApi/appsettings.Development.json

SERVICE: TokenService and Development.json Created

---

src/GreenSale.Persistence/Dtos/Security/VerificationDto.cs
src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.Service/Service/Notifications/SmsSender.cs
src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/User/AuthController.cs

PERSISTENCE : Dtos Security VerificationDto
SERVICE : Servise-Notification-SmsSender
Wep.Api Controller AuthController
close #27 #26

SERVICE : Servise-Auth-Authservie-SendCodeForRegisterAsync

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Security/PasswordHasher.cs

SERVICE: PasswordHasher Created

---

src/GreenSale.Service/Helpers/CodeGenerator.cs

SERVICE: CodeGenerator Created

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Helpers/MediaHelper.cs

MediaHelper Create

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Service/Categories/CategoryService.cs

CategoryService Created

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Interfaces/Common/IFileService.cs
src/GreenSale.Service/Service/Common/FileService.cs

SERVICE:FileService (Delete func) Created

---

src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Service/Auth/IdentityService.cs

IdentityService Created

---

src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
src/GreenSale.Domain/Entites/Users/User.cs
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.Service/Service/Notifications/SmsSender.cs
src/GreenSale.WebApi/Controllers/User/AuthController.cs

SERVICE : Servise-Auth-Authservie-VerifyRegisterAsync

---

src/GreenSale.Domain/Entites/Categories/Category.cs
src/GreenSale.Persistence/Validators/Categories/CategoryCreateValidator.cs
src/GreenSale.Service/Interfaces/Categories/ICategoryService.cs
src/GreenSale.Service/Service/Categories/CategoryService.cs
src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs

Full CategoryController Created

---

src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
src/GreenSale.Persistence/Validators/Dtos/AuthUserValidators/UserLoginValidator.cs
src/GreenSale.Persistence/Validators/Dtos/AuthUserValidators/UserRegisterValidator.cs
src/GreenSale.WebApi/Controllers/User/AuthController.cs

WEBAPI : Add Auth Controller Validayion

---

src/GreenSale.WebApi/Middlewares/ExceptionHandlerMiddleware.cs
src/GreenSale.WebApi/Program.cs

Middleware Created

---

src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs
src/GreenSale.WebApi/Controllers/Common/Auth/AuthController.cs
src/GreenSale.WebApi/Controllers/Common/BaseController.cs

WEP-API: Architekture in Controller close #54

WEP-API Architekture Controller

---

src/GreenSale.Application/Exceptions/Roles/RoleNotFoundException.cs
src/GreenSale.Service/Interfaces/Roles/IRoleService.cs
src/GreenSale.Service/Service/Categories/CategoryService.cs
src/GreenSale.Service/Service/Roles/RoleService.cs

RoleService and RoleException Created

---

src/GreenSale.Persistence/Common/Helpers/MediaHelper.cs
src/GreenSale.Persistence/Dtos/StoragDtos/StoragCreateDto.cs
src/GreenSale.Persistence/Validators/Storages/StorageCreateValidator.cs

PERSISTENCE: StorageCretaeValidator Create

---

src/GreenSale.Persistence/Dtos/StoragDtos/StoragUpdateDto.cs
src/GreenSale.Persistence/Validators/Storages/StorageUpdateValidator.cs

PERSISTENCE: StorageUpdateValidator Create

---

src/GreenSale.DataAccess/Repositories/Storages/StorageRepository.cs
src/GreenSale.Persistence/Dtos/StoragDtos/StoragCreateDto.cs
src/GreenSale.Service/Service/Common/FileService.cs
src/GreenSale.Service/Service/Storages/StorageService.cs
src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/Common/Storages/StorageController.cs
src/GreenSale.WebApi/GreenSale.WebApi.csproj

WEBAPI: StorageController Created

---

src/GreenSale.Application/Exceptions/ImageNotFoundException.cs
src/GreenSale.DataAccess/Repositories/Roles/RoleRepositories.cs
src/GreenSale.Persistence/Validators/Roles/RoleValidator.cs
src/GreenSale.Persistence/Validators/Storages/StorageCreateValidator.cs
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.Service/Service/Auth/TokenService.cs
src/GreenSale.Service/Service/Common/FileService.cs
src/GreenSale.Service/Service/Notifications/SmsSender.cs
src/GreenSale.Service/Service/Storages/StorageService.cs
src/GreenSale.WebApi/Configurations/Layers/CorsPolicyConfiguration.cs
src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/Admin/Roles/RoleController.cs
src/GreenSale.WebApi/Controllers/Common/Storages/StorageController.cs
src/GreenSale.WebApi/Program.cs

User Created Full

---

src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
src/GreenSale.Persistence/Dtos/Auth/ForgotPassword.cs
src/GreenSale.Service/Interfaces/Auth/IAuthServices.cs
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.WebApi/Controllers/Admin/Categories/AdminCategoriesController.cs
src/GreenSale.WebApi/Controllers/Admin/Roles/AdminRolesController.cs
src/GreenSale.WebApi/Controllers/Auth/AuthController.cs
src/GreenSale.WebApi/Controllers/Client/ClientStoragesController.cs
src/GreenSale.WebApi/Controllers/Common/Auth/AuthController.cs
src/GreenSale.WebApi/Controllers/Common/Categories/CommonCategoriesController.cs
src/GreenSale.WebApi/Controllers/Common/Storages/CommonStoragesController.cs
src/GreenSale.WebApi/Program.cs

SERVICE : Auth Reset PAssword Complate

---

src/GreenSale.DataAccess/Interfaces/Roles/IUserRoles.cs
src/GreenSale.DataAccess/Repositories/Roles/UserRoleRepository.cs
src/GreenSale.DataAccess/ViewModels/UserRoles/UserRoleViewModel.cs
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.WebApi/Configurations/CorsPolicyConfiguration.cs
src/GreenSale.WebApi/Configurations/JwtConfiguration.cs
src/GreenSale.WebApi/Configurations/SwaggerAuthConfiguration.cs
src/GreenSale.WebApi/GreenSale.WebApi.csproj
src/GreenSale.WebApi/Program.cs

WEBAPI : auftariza Super Admin And Admin

---

src/GreenSale.DataAccess/Repositories/Roles/UserRoleRepository.cs
src/GreenSale.Service/Service/Roles/UserRoleService.cs
src/GreenSale.WebApi/Configurations/JwtConfiguration.cs
src/GreenSale.WebApi/Controllers/Heat/SuperAdminBaseController.cs
src/GreenSale.WebApi/appsettings.json

CODE RUB : Authtariza User To Admin

---

src/GreenSale.Service/Interfaces/Users/IUserService.cs
src/GreenSale.Service/Service/Auth/AuthServise.cs
src/GreenSale.Service/Service/Users/UserService.cs

SERVICE : User Interface and User Service Created

---

src/GreenSale.Persistence/Dtos/UserDtos/UserUpdateDto.cs
src/GreenSale.Persistence/Validators/Users/UserUpdateValidator.cs
src/GreenSale.Service/Interfaces/Users/IUserService.cs
src/GreenSale.Service/Service/Users/UserService.cs

PERSISTENCE : Valodators User Update Validators

---

src/GreenSale.Persistence/Dtos/SellerPostImageUpdateDtos/SellerPostImageUpdateDto.cs
src/GreenSale.Persistence/Dtos/SellerPostsDtos/SellerPostUpdateDto.cs
src/GreenSale.Service/Interfaces/SellerPosts/ISellerPostService.cs
src/GreenSale.Service/Service/Auth/IdentityService.cs
src/GreenSale.Service/Service/Common/FileService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
src/GreenSale.WebApi/GreenSale.WebApi.csproj

Write sellerPost Servise, and Code rub IFILE Service , ISellePostService

---

src/GreenSale.Persistence/Dtos/BuyerPostImageUpdateDtos/BuyerPostImageDto.cs
src/GreenSale.Service/GreenSale.Service.csproj
src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs

PERSISTENCE : Buyer Post Image Update Dto Creted

SERVICE : Buyer Post Service Create 

---

src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostImageRepository.cs
src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostRepository.cs
src/GreenSale.Domain/Entites/SellerPosts/SellerPostImage.cs
src/GreenSale.Service/Interfaces/Users/IUserService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
src/GreenSale.Service/Service/Users/UserService.cs
src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/Admin/Users/AdminUsersController.cs
src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostController.cs
src/GreenSale.WebApi/Controllers/Client/Storages/ClientStoragesController.cs
src/GreenSale.WebApi/Controllers/Common/Categories/CommonCategoriesController.cs
src/GreenSale.WebApi/Controllers/Common/SellerPosts/CommonSellerPostController.cs
src/GreenSale.WebApi/Controllers/Common/Storages/CommonStoragesController.cs
src/GreenSale.WebApi/Program.cs

2-Code Rub : sellerpost Repository update
3 - code Rub : SellerPostImage
4- code rub : IUserService
5- code rub : SellerPostService createasyn
6- UserService : add IIdentity service
7- DataAccessConfiguration : add repository
8 - ServiceLayerConfiguration : add service
9- Code Rub: AdminUsersController
10- code rub : ClientAccountController update
11- admin : add ClientSellerPostController
12- client : add ClientStoragesController
13- Code Rub : CommonCategoriesController add count and change BaseController 14 - Common add CommonSellerPostController
15 - code Rub : Common CommonStoragesController
close #95

WEBAPI : Seller Post Controller

---

src/GreenSale.Persistence/Validators/BuyerPosts/BuyerPostCreateValidator.cs
src/GreenSale.WebApi/GreenSale.WebApi.csproj

PERSISTENCE: BuyerPostCreateValidator Create

---

src/GreenSale.Persistence/Validators/BuyerPosts/BuyerPostUpdateValidator.cs

PERSISTENCE: BuyerPostImage Created

---

src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
src/GreenSale.WebApi/Controllers/Common/BuyerPosts/CommonBuyerPostsController.cs

BuyerPostController Created

---

src/GreenSale.DataAccess/Interfaces/Roles/IUserRoles.cs
src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostController.cs
src/GreenSale.WebApi/Controllers/Common/BuyerPosts/CommonBuyerPostsController.cs

CODE RUB : Controller

---

src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
src/GreenSale.DataAccess/ViewModels/Users/UserViewModel.cs
src/GreenSale.Service/Service/Users/UserService.cs
src/GreenSale.WebApi/Controllers/Client/BaseClientController.cs
src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs

WEBAPI : Client Controller Get User

---

src/GreenSale.Persistence/Validators/Users/UserUpdateValidator.cs
src/GreenSale.WebApi/Configurations/CorsPolicyConfiguration.cs
src/GreenSale.WebApi/Program.cs

CODE RUB : Cors check amd programs

---

src/GreenSale.DataAccess/Interfaces/SellerPosts/ISellerPostImageRepository.cs
src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostImageRepository.cs
src/GreenSale.DataAccess/ViewModels/SellerPosts/SellerPostViewModel.cs
src/GreenSale.Persistence/Validators/Users/UserUpdateValidator.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs

CODE RUB : Service Seller Post GetAll GetById

---

src/GreenSale.DataAccess/Repositories/Roles/RoleRepositories.cs
src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
src/GreenSale.Service/Service/Storages/StorageService.cs

AUTH Fixed Some Bugs In

---

src/GreenSale.Domain/Entites/BuyerPosts/BuyerPostStars.cs

DOMAIN : Adding Buyer Post Starts To Entity

---

src/GreenSale.Domain/Entites/BuyerPosts/BuyerPostStars.cs
src/GreenSale.Domain/Entites/SellerPosts/SellerPostStars.cs

DOMAIN : Adding Seller Post Starts To Entity

---

src/GreenSale.Domain/Entites/Storages/StoragePostStars.cs

DOMAIN : Adding Storage Post Starts To Entity

---

src/GreenSale.DataAccess/Interfaces/BuyerPosts/IBuyerPostStarRepository.cs
src/GreenSale.DataAccess/Interfaces/SellerPosts/ISellerPostStarRepository.cs
src/GreenSale.DataAccess/Interfaces/Storages/IStorageStarRepository.cs

DATAACCESS : Writing An Interface To The Post Stars

---

src/GreenSale.DataAccess/Interfaces/BuyerPosts/IBuyerPostStarRepository.cs
src/GreenSale.DataAccess/Interfaces/SellerPosts/ISellerPostStarRepository.cs
src/GreenSale.DataAccess/Interfaces/Storages/IStorageStarRepository.cs
src/GreenSale.DataAccess/Repositories/BuyerPosts/BuyerPostStarRepository.cs
src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostStarRepository.cs
src/GreenSale.DataAccess/Repositories/Storages/StorageStarRepository.cs

DATAACCESS : Writing An Repositories To The Post Stars

---

src/GreenSale.Domain/Entites/SellerPosts/SellerPostStars.cs
src/GreenSale.Service/Interfaces/SellerPosts/ISellerPostStarService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostStarService.cs

SERVICE : Writing Service For Seller Post Stars

---

src/GreenSale.Domain/Entites/Storages/StoragePostStars.cs
src/GreenSale.Service/Interfaces/Storages/IStoragePostStarService.cs
src/GreenSale.Service/Service/Storages/StoragePostStarService.cs

Service : Interface AND Sevice Write

---

src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostStarController.cs
src/GreenSale.WebApi/Controllers/Client/StoragePosts/ClientStoragePostStarController.cs

WEBAPI : Write Storage Star Controller

---

src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.DataAccess/ViewModels/BuyerPosts/BuyerPostViewModel.cs
src/GreenSale.DataAccess/ViewModels/SellerPosts/SellerPostViewModel.cs
src/GreenSale.DataAccess/ViewModels/Storages/StoragesViewModel.cs

Domain : Adding properties to ViewModels

---

src/GreenSale.DataAccess/Interfaces/BuyerPosts/IBuyerPostStarRepository.cs
src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.DataAccess/Repositories/BuyerPosts/BuyerPostStarRepository.cs
src/GreenSale.DataAccess/ViewModels/BuyerPosts/BuyerPostViewModel.cs
src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostStarService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostStarService.cs

SERVICE : Add Avarage Stars Buyer Post

---

src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostStarService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostStarService.cs

SERVICE : Add User Star In Buyer Post

---

src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostStarController.cs
src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostStarController.cs
src/GreenSale.WebApi/Controllers/Client/StoragePosts/ClientStoragePostStarController.cs

Fixed Stars Route And FromFile

---

src/GreenSale.DataAccess/Interfaces/BuyerPosts/IBuyerPostStarRepository.cs
src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.DataAccess/Repositories/BuyerPosts/BuyerPostStarRepository.cs
src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostStarService.cs
src/GreenSale.Service/Interfaces/SellerPosts/ISellerPostStarService.cs
src/GreenSale.Service/Interfaces/Storages/IStoragePostStarService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
src/GreenSale.Service/Service/BuyerPosts/BuyerPostStarService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
src/GreenSale.Service/Service/SellerPosts/SellerPostStarService.cs
src/GreenSale.Service/Service/Storages/StoragePostStarService.cs
src/GreenSale.Service/Service/Storages/StorageService.cs

Fixed Return Type

---

src/GreenSale.Application/Exceptions/PostStars/PostStarAmmountManyException.cs
src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.Persistence/Validators/PostStar/PostStarValidator.cs
src/GreenSale.WebApi/Controllers/Admin/BuyerPosts/AdminBuyerPostStarController.cs
src/GreenSale.WebApi/Controllers/Admin/SellerPosts/AdminSellerPostStarController.cs
src/GreenSale.WebApi/Controllers/Admin/Storages/AdminStorageStarController.cs
src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostStarController.cs
src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostStarController.cs
src/GreenSale.WebApi/Controllers/Client/StoragePosts/ClientStoragePostStarController.cs
src/GreenSale.WebApi/GreenSale.WebApi.csproj

PERSISTENCE : Add Validator Post Star

---

src/GreenSale.DataAccess/Repositories/BaseRepository.cs
src/GreenSale.Persistence/Dtos/StoragDtos/StoragUpdateDto.cs
src/GreenSale.Persistence/Validators/Storages/StorageUpdateValidator.cs
src/GreenSale.Service/Service/Storages/StorageService.cs

Deleted from Update Storage Post Dto  Image
